"""Generate the mod's per-target directive plumbing (#7).

``set_ai_directive`` names a country, but an ``ai_strategy`` block names its
target as a literal (``id = "GER"``): Paradox script has no variable-driven
``id`` that is known to work in this scope. The hand-written blocks therefore
hardcoded example targets, and "protect Finland" biased the AI toward whatever
tag the file happened to contain -- the hybrid layer existing without working.

So the certain-but-verbose route: one ``ai_strategy`` block per (directive,
target), each gated on its own country flag, generated from a template. Raising
a directive is two stable clicks rather than one decision per pair:

1. ``Target: POL`` -- a decision that makes POL the selected target;
2. ``Directive: protect`` -- a decision that raises ``protect`` against
   whichever target is selected, by setting ``llmb_protect_POL``.

That keeps the decision list at (targets + directives) entries instead of their
product, and keeps the harness side untouched: ``set_ai_directive`` in the
catalog does not know any of this exists.

The tag list defaults to the countries a 1936 campaign most plausibly names;
regenerate with ``hoi4-harness mod-directives --tags ...`` for a playset with
others (a total conversion, for one). Output is deterministic, and a test fails
when the committed files drift from what this module would write.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .actions.catalog import AI_DIRECTIVES

#: The countries a vanilla campaign most plausibly names in a directive.
DEFAULT_TAGS = (
    "GER", "ENG", "FRA", "ITA", "SOV", "USA", "JAP", "CHI", "PRC", "MAN",
    "POL", "CZE", "AUS", "HUN", "ROM", "YUG", "GRE", "BUL", "ALB", "TUR",
    "SPR", "POR", "BEL", "HOL", "LUX", "DEN", "NOR", "SWE", "FIN", "EST",
    "LAT", "LIT", "SWI", "IRE", "CAN", "AST", "NZL", "SAF", "RAJ", "SIA",
    "PHI", "MEX", "BRA", "ARG", "PER", "IRQ", "SAU", "EGY", "ETH",
)

#: Directive -> the ai_strategy entries it raises, as (type, value).
#: VERIFY against common/ai_strategy in your install: an unrecognised type is
#: ignored silently, so a wrong name here is a directive that does nothing --
#: which the brief's directive-effect line (#11) is there to reveal.
STRATEGIES: dict[str, tuple[tuple[str, int], ...]] = {
    "invade": (("conquer", 150), ("invade", 150)),
    "protect": (("protect", 150),),
    "contain": (("contain", 150),),
    "befriend": (("befriend", 150),),
    "antagonize": (("antagonize", 150),),
    "ignore": (("ignore", 150),),
}

#: Event codes the generated effects emit; mirrored in adapters/logtail.py.
EVENT_TARGET_SELECTED = 13
EVENT_DIRECTIVE_RAISED = 14

HEADER = (
    "# GENERATED by `hoi4-harness mod-directives` from src/hoi4_harness/modgen.py.\n"
    "# Do not edit by hand: change the generator and regenerate.\n"
)


@dataclass(frozen=True)
class GeneratedFile:
    path: str          # relative to the mod root (mod/llm_bridge)
    text: str
    bom: bool = False  # HOI4 reads localisation only as UTF-8 with a BOM


def generate(tags: tuple[str, ...] | list[str] = DEFAULT_TAGS) -> list[GeneratedFile]:
    tags = tuple(dict.fromkeys(tag.strip().upper() for tag in tags if tag.strip()))
    for tag in tags:
        if not (len(tag) == 3 and tag.isalnum()):
            raise ValueError(f"{tag!r} is not a country tag (three letters or digits)")
    missing = set(AI_DIRECTIVES) - set(STRATEGIES)
    if missing:
        raise ValueError(f"no ai_strategy mapping for directive(s): {', '.join(sorted(missing))}")
    return [
        GeneratedFile("common/ai_strategy/llm_bridge_targets.txt", _strategies(tags)),
        GeneratedFile("common/scripted_effects/llm_bridge_targets.txt", _effects(tags)),
        GeneratedFile("common/decisions/llm_bridge_target_decisions.txt", _decisions(tags)),
        GeneratedFile(
            "localisation/english/llm_bridge_targets_l_english.yml", _localisation(tags), bom=True
        ),
    ]


def write(mod_dir: Path, tags=DEFAULT_TAGS) -> list[Path]:
    written = []
    for item in generate(tags):
        target = mod_dir / item.path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(item.text, encoding="utf-8-sig" if item.bom else "utf-8", newline="\n")
        written.append(target)
    return written


def drift(mod_dir: Path, tags=DEFAULT_TAGS) -> list[str]:
    """Generated files whose committed copy differs from what would be written."""
    stale = []
    for item in generate(tags):
        target = mod_dir / item.path
        current = target.read_text(encoding="utf-8-sig") if target.exists() else None
        if current != item.text:
            stale.append(item.path)
    return stale


# --- the four files ----------------------------------------------------------


def _strategies(tags: tuple[str, ...]) -> str:
    out = [
        HEADER,
        "# One block per (directive, target), each gated on its own flag. The",
        "# harness-side vocabulary is set_ai_directive {directive, target}.",
        "",
    ]
    for directive in AI_DIRECTIVES:
        for tag in tags:
            flag = f"llmb_{directive}_{tag}"
            out.append(f"{flag} = {{")
            out.append(f"\tenable = {{ has_country_flag = {flag} }}")
            out.append(f"\tabort = {{ NOT = {{ has_country_flag = {flag} }} }}")
            for kind, value in STRATEGIES[directive]:
                out.append(f'\tai_strategy = {{ type = {kind} id = "{tag}" value = {value} }}')
            out.append("}")
            out.append("")
    return "\n".join(out)


def _effects(tags: tuple[str, ...]) -> str:
    out = [HEADER, "llm_bridge_clear_target = {"]
    out += [f"\tclr_country_flag = llmb_target_{tag}" for tag in tags]
    out += ["}", ""]
    for tag in tags:
        out += [
            f"llm_bridge_select_{tag} = {{",
            "\tllm_bridge_clear_target = yes",
            f"\tset_country_flag = llmb_target_{tag}",
            f"\tset_variable = {{ llmb_event_kind = {EVENT_TARGET_SELECTED} }}",
            "\tllm_bridge_emit_event = yes",
            "}",
            "",
        ]
    for directive in AI_DIRECTIVES:
        out.append(f"llm_bridge_raise_{directive} = {{")
        for tag in tags:
            out.append(
                f"\tif = {{ limit = {{ has_country_flag = llmb_target_{tag} }} "
                f"set_country_flag = llmb_{directive}_{tag} }}"
            )
        out += [
            f"\tset_variable = {{ llmb_event_kind = {EVENT_DIRECTIVE_RAISED} }}",
            "\tllm_bridge_emit_event = yes",
            "}",
            "",
        ]
    out.append("llm_bridge_clear_target_directives = {")
    for directive in AI_DIRECTIVES:
        out += [f"\tclr_country_flag = llmb_{directive}_{tag}" for tag in tags]
    out += ["\tllm_bridge_clear_target = yes", "}", ""]
    return "\n".join(out)


def _decision(name: str, effect: str) -> list[str]:
    return [
        f"\t{name} = {{",
        "\t\ticon = generic_political_actions",
        "\t\tcost = 0",
        "\t\tfire_only_once = no",
        "\t\tdays_re_enable = 0",
        "\t\tavailable = { always = yes }",
        "\t\tcomplete_effect = {",
        f"\t\t\t{effect} = yes",
        "\t\t}",
        "\t\tai_will_do = { factor = 0 }",
        "\t}",
        "",
    ]


def _decisions(tags: tuple[str, ...]) -> str:
    out = [
        HEADER,
        "# Pick a target, then a directive: targets + directives decisions rather",
        "# than their product. Instant, free and idempotent, like the rest of the",
        "# bridge's decisions, so a mis-click costs nothing.",
        "",
        "llm_bridge_target_category = {",
        "",
    ]
    for tag in tags:
        out += _decision(f"llmb_target_{tag}", f"llm_bridge_select_{tag}")
    for directive in AI_DIRECTIVES:
        out += _decision(f"llmb_directive_{directive}", f"llm_bridge_raise_{directive}")
    out.append("}")
    out.append("")
    return "\n".join(out)


def _localisation(tags: tuple[str, ...]) -> str:
    lines = [
        "l_english:",
        ' llm_bridge_target_category:0 "LLM Bridge: targets"',
        ' llm_bridge_target_category_desc:0 "Choose a country, then a directive to raise against it."',
    ]
    for tag in tags:
        lines.append(f' llmb_target_{tag}:0 "Target: {tag}"')
        lines.append(f' llmb_target_{tag}_desc:0 "Make {tag} the target of the next directive."')
    for directive in AI_DIRECTIVES:
        lines.append(f' llmb_directive_{directive}:0 "Directive: {directive}"')
        lines.append(
            f' llmb_directive_{directive}_desc:0 "Tell the AI to {directive} the selected target."'
        )
    return "\n".join(lines) + "\n"
